# version: "3.9"

services:
  app:
  #build docker file inside directory
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
    #makes the changes in code to reflect real time, no rebuild needed
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"